services:
  # frontend:
  #   image: frontend:test
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #     - voice-generation
  #   env_file:
  #     - frontend/.env

  backend:
    # image: wzj5235/audio-chat-backend:latest
    image: wzj5235/audio-chat-backend:test
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  # voice-generation:
  #   image: wzj5235/voice-generation:latest
  #   # image: wzj5235/voice-generation:test
  #   ports:
  #     - "9880:9880"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4G
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  # mysql:
  #   image: wzj5235/audio-chat-mysql:latest
  #   ports:
  #     - "3306:3306"
  #   env_file:
  #     - backend/.env
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 5s
  
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\\Users\\Administrator\\Desktop\\mongodb_data
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\\Users\\Administrator\\Desktop\\redis_data

