services:

  backend:
    image: wzj5235/audio-chat-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ~/.env

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    env_file:
      - ~/.env
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ~/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/mongodb_data
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/redis_data
