version: '2'

services:
  # frontend:
  #   image: wzj5235/audio-chat-frontend:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #     - voice-generation
  #   env_file:
  #     - /root/.env.frontend

  backend:
    image: wzj5235/audio-chat-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - /home/ubuntu/.env

  # voice-generation:
  #   image: wzj5235/voice-generation:latest
  #   ports:
  #     - "9880:9880"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4G
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  mysql:
    image: wzj5235/audio-chat-mysql:latest
    env_file:
      - /home/ubuntu/.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s