name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build backend Docker image
      run: docker build -t wzj5235/audio-chat-backend:latest ./backend

    - name: Push backend Docker image to Docker Hub
      run: docker push wzj5235/audio-chat-backend:latest
