name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build backend Docker image
      run: docker build -t wzj5235/audio-chat-backend:latest ./backend

    - name: Push backend Docker image to Docker Hub
      run: docker push wzj5235/audio-chat-backend:latest

    - name: Setup SSH
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Run commands on server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        ssh -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
        echo "docker compose up -d"
        docker compose up -d
        EOF
