name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build
      working-directory: ./frontend
      run: npm run build

    - name: Tar frontend
      working-directory: ./frontend
      run: tar -czvf frontend.tar.gz build

    - name: Setup SSH
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts


    - name: Use scp to upload frontend
      working-directory: ./frontend
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        scp -i ~/.ssh/id_rsa frontend.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/frontend.tar.gz

    - name: Run commands on server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        ssh -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
        cd /root
        tar -xzvf frontend.tar.gz
        rm frontend.tar.gz
        rm -rf /var/www/html/*
        mv build/* /var/www/html/
        rm -rf build
        systemctl restart nginx
        EOF
